version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Varaprasad123
      POSTGRES_DB: devconnect
    ports:
      - '5434:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3004:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  db-data:
