version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Varaprasad123
      POSTGRES_DB: devconnect
    ports:
      - '5434:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: devconnect-backend
    ports:
      - '3004:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:Varaprasad123@db:5432/devconnect
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:7
    container_name: devconnect-redis
    ports:
      - "6379:6379"

volumes:
  db-data:
